### ISSUE TITLE
Unable to list computers: list index out of range

### ISSUE THREAD

**Issue by dkjajhqu2h3j** [asmtlab/snafflepy#37]
### Current Behavior

Snafflepy is unable to list computers and thereafter errors out.

### Expected Behavior

Snafflepy should work as expected.

### Steps to Reproduce

1. Simply execute the tool using for example "python3 snaffler.py dc1.adlab1.local -d adlab1.local -u adlab1_domainuser1 -p 'Passw0rd!' -v".

![snafflepy1](https://github.com/asmtlab/snafflepy/assets/153735386/0bd68e64-197f-4e60-aacd-7df160fdc942)

**Comment by robert-todora** [comment]
Fixed in #39 thank you @Hackndo
